# -*- coding: utf-8 -*-
"""DDPM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSkFSOxRItAOQjsYLLjsRQ7MX9EFLfXn
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import save_image
import os

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
BATCH_SIZE = 128
EPOCHS = 5
TIMESTEPS = 1000
LR = 1e-3
TIME_EMB_DIM = 32

print(f"Using device: {DEVICE}")

class LinearNoiseScheduler:
    def __init__(self, timesteps=1000, beta_start=1e-4, beta_end=0.02):
        self.timesteps = timesteps
        self.beta = torch.linspace(beta_start, beta_end, timesteps)
        self.alpha = 1.0 - self.beta
        self.alpha_cumprod = torch.cumprod(self.alpha, dim=0)

    def add_noise(self, x_0, t):
        device = x_0.device
        alpha_cumprod_t = self.alpha_cumprod.to(device)[t].view(-1, 1, 1, 1)
        noise = torch.randn_like(x_0)
        noisy_x = torch.sqrt(alpha_cumprod_t) * x_0 + torch.sqrt(1.0 - alpha_cumprod_t) * noise
        return noisy_x, noise

class SinusoidalPositionEmbeddings(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, time):
        device = time.device
        half_dim = self.dim // 2
        embeddings = torch.log(torch.tensor(10000.0)) / (half_dim - 1)
        embeddings = torch.exp(torch.arange(half_dim, device=device) * -embeddings)
        embeddings = time[:, None] * embeddings[None, :]
        embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)
        return embeddings

class ResNetBlock(nn.Module):
    def __init__(self, in_c, out_c, time_emb_dim):
        super().__init__()
        self.time_mlp = nn.Linear(time_emb_dim, out_c)
        self.conv1 = nn.Conv2d(in_c, out_c, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(out_c, out_c, kernel_size=3, padding=1)
        self.norm1 = nn.GroupNorm(8, out_c)
        self.norm2 = nn.GroupNorm(8, out_c)
        self.act = nn.SiLU()
        self.residual_input = nn.Conv2d(in_c, out_c, 1) if in_c != out_c else nn.Identity()

    def forward(self, x, t_emb):
        h = self.act(self.norm1(self.conv1(x)))
        time_proj = self.act(self.time_mlp(t_emb))[(..., ) + (None, ) * 2]
        h = h + time_proj
        h = self.act(self.norm2(self.conv2(h)))
        return h + self.residual_input(x)

class SimpleUNet(nn.Module):
    def __init__(self, in_channels=1, time_emb_dim=32):
        super().__init__()
        self.time_mlp = nn.Sequential(
            SinusoidalPositionEmbeddings(time_emb_dim),
            nn.Linear(time_emb_dim, time_emb_dim),
            nn.SiLU()
        )

        # Encoder
        self.down1 = ResNetBlock(in_channels, 64, time_emb_dim)
        self.pool1 = nn.MaxPool2d(2)
        self.down2 = ResNetBlock(64, 128, time_emb_dim)
        self.pool2 = nn.MaxPool2d(2)

        # Bottleneck
        self.bottleneck = ResNetBlock(128, 128, time_emb_dim)

        # Decoder
        self.up1 = nn.ConvTranspose2d(128, 64, kernel_size=2, stride=2) # 7x7 -> 14x14
        self.up_block1 = ResNetBlock(192, 64, time_emb_dim)

        self.up2 = nn.ConvTranspose2d(64, 32, kernel_size=2, stride=2)  # 14x14 -> 28x28
        self.up_block2 = ResNetBlock(32 + 64, 32, time_emb_dim)

        self.final_conv = nn.Conv2d(32, in_channels, kernel_size=1)

    def forward(self, x, t):
        t_emb = self.time_mlp(t)

        # Encoder
        x1 = self.down1(x, t_emb)
        x2 = self.down2(self.pool1(x1), t_emb)

        # Bottleneck
        b = self.bottleneck(self.pool2(x2), t_emb)

        # u1 = torch.cat([u1, x2], dim=1)

        # Decoder with Skip Connections
        u1 = self.up1(b)
        # print("u1:", u1.shape)
        # print("x2:", x2.shape)
        u1 = torch.cat([u1, x2], dim=1)
        # print("After concat:", u1.shape)
        u1 = self.up_block1(u1, t_emb)

        u2 = self.up2(u1)
        # print("u2:", u2.shape)
        # print("x1:", x1.shape)
        u2 = torch.cat([u2, x1], dim=1)
        # print("After concat:", u2.shape)
        u2 = self.up_block2(u2, t_emb)

        return self.final_conv(u2)

@torch.no_grad()
def generate_samples(model, scheduler, num_samples=16, filename="ddpm_generated.png"):
    model.eval()
    x = torch.randn((num_samples, 1, 28, 28), device=DEVICE)

    for t in reversed(range(scheduler.timesteps)):
        t_batch = torch.full((num_samples,), t, device=DEVICE, dtype=torch.long)
        predicted_noise = model(x, t_batch)

        alpha = scheduler.alpha.to(DEVICE)[t]
        alpha_cumprod = scheduler.alpha_cumprod.to(DEVICE)[t]
        beta = scheduler.beta.to(DEVICE)[t]

        # Compute mean x_{t-1}
        x = (1 / torch.sqrt(alpha)) * (x - (beta / torch.sqrt(1 - alpha_cumprod)) * predicted_noise)

        # Add noise if not at final timestep
        if t > 0:
            z = torch.randn_like(x)
            x = x + torch.sqrt(beta) * z

    # Denormalize [-1, 1] back to [0, 1] for saving image
    x = (x + 1) / 2
    x = torch.clamp(x, 0, 1)
    save_image(x, filename, nrow=4)
    print(f"Generated samples saved to: {filename}")
    model.train()

def main():
    # Dataset Preparation (Scaled to [-1, 1])
    transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
    ])
    dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
    dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)
    # print(dataset)
    # print(dataloader)
    # classes = dataset.classes
    # print(classes)
    # print(dataset.data.shape)
    # image, label = dataset[121]

    # print(image.shape)
    # print(label)
    # print(len(dataloader))
        # batch = next(iter(dataloader))
    # print(type(batch))
    # images, labels = batch
    # print(images.shape)
    # print(labels.shape)
    # print(labels)
    # import matplotlib.pyplot as plt

    # fig, axes = plt.subplots(2, 5, figsize=(12, 5))

    # for i, ax in enumerate(axes.flat):
    #     image, label = dataset[i]

    #     image = image.permute(1, 2, 0)
    #     image = image * 0.5 + 0.5

    #     ax.imshow(image)
    #     ax.set_title(classes[label])
    #     ax.axis("off")

    # plt.show()
    scheduler = LinearNoiseScheduler(timesteps=TIMESTEPS)
    # # print(scheduler)
    model = SimpleUNet(in_channels=1, time_emb_dim=TIME_EMB_DIM).to(DEVICE)
    # # print(model)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
    # print(optimizer)
    print("Beginning Training Loop...")
    for epoch in range(1, EPOCHS + 1):
        total_loss = 0.0
        for step, (images, _) in enumerate(dataloader):
            images = images.to(DEVICE)
            optimizer.zero_grad()

            # 1. Sample random timestep t for each image
            t = torch.randint(0, TIMESTEPS, (images.size(0),), device=DEVICE).long()

            # 2. Corrupt image with Gaussian noise
            noisy_images, noise = scheduler.add_noise(images, t)

            # 3. Predict noise using U-Net
            predicted_noise = model(noisy_images, t)
    # print(noisy_images.shape,"----",noise.shape)
    # print(predicted_noise.shape)
            # 4. Calculate MSE Loss
            loss = F.mse_loss(noise, predicted_noise)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        avg_loss = total_loss / len(dataloader)
        print(f"Epoch [{epoch}/{EPOCHS}] - Average MSE Loss: {avg_loss:.5f}")

    print("\nTraining Complete! Generating sample grid...")
    generate_samples(model, scheduler, num_samples=16, filename="ddpm_mnist_output.png")

if __name__ == "__main__":
    main()

